USE CVGS;
INSERT INTO dbo.[Picture] (Title, Description, Location) VALUES ('BLANK', 'BLANK', 'BLANK');
INSERT INTO dbo.[Picture] (Title, Description, Location) VALUES ('BLANK', 'BLANK', 'BLANK');
INSERT INTO dbo.[Picture] (Title, Description, Location) VALUES ('BLANK', 'BLANK', 'BLANK');
INSERT INTO dbo.[Picture] (Title, Description, Location) VALUES ('iconReceived', 'iconReceived', 'iconReceived');
INSERT INTO dbo.[Picture] (Title, Description, Location) VALUES ('iconPaymentProcessed', 'iconPaymentProcessed', 'iconPaymentProcessed');
INSERT INTO dbo.[Picture] (Title, Description, Location) VALUES ('iconPaymentError', 'iconPaymentError', 'iconPaymentError');
INSERT INTO dbo.[Picture] (Title, Description, Location) VALUES ('iconProcessed', 'iconProcessed', 'iconProcessed');
INSERT INTO dbo.[Picture] (Title, Description, Location) VALUES ('iconEmployee', 'iconEmployee', 'iconEmployee');
INSERT INTO dbo.[Picture] (Title, Description, Location) VALUES ('iconCustomer', 'iconCustomer', 'iconCustomer');
INSERT INTO dbo.[Picture] (Title, Description, Location) VALUES ('BLANK', 'BLANK', 'BLANK');
INSERT INTO dbo.[Picture] (Title, Description, Location) VALUES ('BLANK', 'BLANK', 'BLANK');
INSERT INTO dbo.[Picture] (Title, Description, Location) VALUES ('BLANK', 'BLANK', 'BLANK');
INSERT INTO dbo.[Picture] (Title, Description, Location) VALUES ('BLANK', 'BLANK', 'BLANK');
INSERT INTO dbo.[Picture] (Title, Description, Location) VALUES ('iconApproved', 'iconApproved', 'iconApproved');
INSERT INTO dbo.[Picture] (Title, Description, Location) VALUES ('iconDenied', 'iconEDenied', 'iconDenied');
INSERT INTO dbo.[Picture] (Title, Description, Location) VALUES ('iconAwaitingApproval', 'iconAwaitingApproval', 'iconAwaitingApproval');
INSERT INTO dbo.[Picture] (Title, Description, Location) VALUES ('iconBlocked', 'iconBlocked', 'iconBlocked');
INSERT INTO dbo.[Picture] (Title, Description, Location) VALUES ('BLANK', 'BLANK', 'BLANK');
INSERT INTO dbo.[Picture] (Title, Description, Location) VALUES ('iconAwatingReviewApproval', 'iconAwaiting', 'iconAwaiting');
INSERT INTO dbo.[Picture] (Title, Description, Location) VALUES ('BLANK', 'BLANK', 'BLANK');
INSERT INTO dbo.[Picture] (Title, Description, Location) VALUES ('iconReviewApproved', 'iconReviewApproved', 'iconReviewApproved');
INSERT INTO dbo.[Picture] (Title, Description, Location) VALUES ('iconReviewRejected', 'iconReviewRejected', 'iconReviewRejected');
DELETE FROM dbo.[Picture] WHERE Title = 'BLANK';

INSERT INTO dbo.[Colour] (Name, Value) VALUES ('RED', '#D0312D');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CHERRY RED', '#990F02');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('ROSE', '#E3242B');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('JAM', '#60100B');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('MERLOT', '#541E1B');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('GARNET', '#610C04');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CRIMSON', '#B90E0A');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('RUBY', '#900603');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SCARLET', '#900D09');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('WINE', '#4E0707');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('BRICK', '#7E2811');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('APPLE', '#A91B0D');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('MAHOGANY', '#420C09');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('BLOOD', '#710C04');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SANGRIA RED', '#5E1916');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('BERRY', '#7A1712');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CURRANT', '#680C07');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('BLUSH RED', '#BC544B');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CANDY', '#D21404');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('LIPSTICK', '#9B1003');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CARMINE', '#960018');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PERSIAN RED', '#CA3433');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('VERMILION', '#7E191B');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Imperial Red', '#ED2939');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Indian Red', '#CD5C5C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Chili Red', '#C21807');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Maroon', '#800000');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Fire Brick', '#B22222');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Desire', '#EA3C53');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Raspberry', '#D21F3C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Candy Apple', '#FF0800');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Hibiscus', '#B43757');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Ferrari', '#FF2800');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Burgundy', '#8D021F');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Dark Red', '#8B0000');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Prismatic Red', '#D03D33');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('49ers Red', '#AA0000');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Cardinals Red', '#BD2031');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Ajax Red', '#D2122E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Alabama Crimson', '#9E1B32');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Alizarin Crimson', '#E32636');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Amaranth Red', '#F4364C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('American Rose', '#FF033E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Angels Red', '#BA0021');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Arsenal Red', '#DB0007');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Auburn Red', '#A52A2A');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('BU Scarlet', '#CC0000');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Bills Red', '#C60C30');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Bittersweet Shimmer', '#BF4F51');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('ORANGE', '#ED7014');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('TANGERINE', '#FA8128');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('MERIGOLD', '#FCAE1E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CIDER', '#B56727');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('RUST', '#8D4004');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('GINGER', '#BE5504');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('TIGER', '#FC6A03');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('FIRE', '#DD571C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('BRONZE', '#B2560D');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CANTALOUPE', '#FDA172');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('APRICOT', '#ED820E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CLAY', '#80400B');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('HONEY', '#EC9706');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CARROT', '#ED7117');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SQUASH', '#C95B0C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SPICE', '#7A3803');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('MARMALADE', '#D16002');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('AMBER', '#893101');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SANDSTONE', '#D67229');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('YAM', '#CC5801');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('TANGELO', '#FC4C02');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('FLAME', '#E34A27');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('FULVOUS', '#E68000');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Dark Orange', '#FF8C00');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Vivid Orange', '#FF5E0E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Orange-Red', '#FF4500');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Metallic Orange', '#E26310');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Pumpkin', '#F5761A');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Smashed Pumpkin', '#FD673A');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('International Orange', '#FF4F00');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Spanish Orange', '#F06105');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Princeton Orange', '#FF8F00');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Deep Saffron', '#FFA52C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Alloy Orange', '#C35214');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Halloween Orange', '#EE5921');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Gamboge', '#E89611');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Medium Vermilion', '#CF5B2E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Pastel Orange', '#FEBA4F');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Philippine Orange', '#F26E01');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Royal Orange', '#FF9944');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Coral', '#FF7F50');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Dark Coral', '#D75341');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Cadmium Orange', '#E6812F');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Rajah', '#FABA5F');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Mango Tango', '#FB8842');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Orange Peel', '#FF9F00');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Vivid Tangelo', '#EC7625');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Persimmon', '#EC5800');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Browns Orange', '#FF3C00');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Burnt Orange', '#CC5500');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('TAN', '#E6DBAC');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('BEIGE', '#EEDC9A');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('MACAROON', '#F9E076');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('HAZEL WOOD', '#C9BB8E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('GRANOLA', '#D6B85A');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('OAT', '#DFC98A');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('EGG NOG', '#FAE29C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('FAWN', '#C8A951');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SUGAR COOKIE', '#F3EAAF');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SAND', '#D8B863');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SEPIA', '#E3B778');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('LATTE', '#E7C27D');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('OYSTER', '#DCD7A0');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('BISCOTTI', '#E3C565');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PARMESAN', '#FDE992');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('HAZELNUT', '#BDA55D');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SANDCASTLE', '#DAC17C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('BUTTERMILK', '#FDEFB2');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SAND DOLLAR', '#EDE8BA');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SHORTBREAD', '#FBE790');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CITRINE', '#E4D00A');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('FLAX', '#EEDC82');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('XANTHIC', '#EEED09');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Sunshine Yellow', '#FFFD37');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Canary Yellow', '#FFEF00');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Lemon Yellow', '#FDFF00');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Pale Goldenrod', '#EEE8AA');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Light Khaki', '#F0E68C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Clover Lime', '#FCE883');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Royal Yellow', '#FADA5E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Gold', '#FFD700');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Safety Yellow', '#EED202');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Laguna', '#F8E473');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Bright Yellow', '#FFFD01');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Greenish Yellow', '#EEEA62');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Sunflower', '#FFDA03');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Bumblebee', '#FCE205');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Butter', '#FFFD74');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Yellow Tan', '#FFE36E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Banana', '#FFE135');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Tuscany', '#FCD12A');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Dijon', '#C49102');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Mustard', '#FEDC56');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Maximum Yellow', '#FAFA37');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Mellow Yellow', '#F8DE7E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Unmellow Yellow', '#FFFF66');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Lemon Curry', '#CCA01D');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Aureolin', '#FDEE00');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Electric Yellow', '#FFFF33');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Pastel Yellow', '#FFFE71');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('GREEN', '#3CB043');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CHARTREUSE', '#B0FC38');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('JUNIPER', '#3A5311');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SAGE', '#728C69');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('LIME', '#AEF359');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('FERN', '#5DBB63');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('OLIVE', '#98BF64');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('EMERALD', '#028A0F');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PEAR', '#74B72E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('MOSS', '#466D1D');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SHAMROCK', '#03AC13');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SEAFOAM', '#3DED97');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PINE', '#234F1E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PARAKEET', '#03C04A');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('MINT', '#99EDC3');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SEAWEED', '#354A21');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PICKLE', '#597D35');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PISTACHIO', '#B2D3C2');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('BASIL', '#32612D');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CROCODILE', '#607D3B');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('AMAZON', '#3B7A57');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('AVOCADO', '#568203');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CELADON', '#ACE1AF');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Forest green', '#0B6623');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Hunter green', '#3F704D');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Artichoke green', '#8F9779');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Jungle green', '#29AB87');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Tropical Rainforest', '#00755E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Persian green', '#00A693');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Sea green', '#2E8B57');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Jade green', '#00A86B');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Laurel green', '#A9BA9D');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Army green', '#4B5320');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Kelly green', '#4CBB17');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Paris green', '#50C878');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Pakistan green', '#006600');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Spring', '#00F0A8');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Chateau', '#48A860');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Swamp', '#A8C090');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Mantis', '#74C365');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Fun', '#007848');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Viridian', '#609078');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Reseda Green', '#6C7C59');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Verdun', '#487800');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Castleton Green', '#00563B');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Bottle Green', '#006A4E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Cadmium Green', '#006B3C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Camouflage Green', '#78866B');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Dollar Bill', '#85BB65');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Inchworm', '#B2EC5D');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('BLUE', '#3944BC');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SLATE', '#757C88');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SKY', '#63C5DA');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('NAVY', '#0A1172');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('INDIGO', '#281E5D');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('COBALT', '#1338BE');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('TEAL', '#48AAAD');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('OCEAN', '#016064');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PEACOCK', '#022D36');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('AZURE', '#1520A6');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CERULEAN', '#0492C2');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('LAPIS', '#2832C2');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SPRUCE', '#2C3E4C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('STONE', '#59788E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('AEGEAN', '#1F456E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('BLUEBERRY', '#241571');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('DENIM', '#151E3D');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('ADMIRAL', '#051094');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SAPPHIRE', '#52B2BF');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('ARCTIC', '#82EEFD');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('TURQUOISE', '#40E0D0');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('STEEL', '#4682B4');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('B’DAZZLED', '#2E5894');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Powder blue', '#B0E0E6');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Baby blue', '#89CFF0');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Beau blue', '#BCD4E6');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Little Boy blue', '#6CA0DC');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Tiffany blue', '#81D8D0');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Carolina blue', '#4B9CD3');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Turkish blue', '#4F97A3');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Maya blue', '#73C2FB');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Cornflower blue', '#6495ED');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Blue Sapphire', '#126180');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Egyptian blue', '#1034A6');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Yale blue', '#00356B');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Space Cadet', '#1D2951');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Imperial blue', '#005A92');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Ruddy blue', '#76ABDF');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Aquamarine Blue', '#6BCAE2');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Argentina Blue', '#6CB4EE');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Astros Navy', '#002D62');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Bayern Blue', '#0066B2');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Berry Blue', '#4F86F7');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Blue Yonder', '#5072A7');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Bleu de France', '#318CE7');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Blue-Gray', '#6699CC');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Boeing Blue', '#0039A6');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Braves Navy', '#13274F');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PURPLE', '#A32CC4');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('MAUVE', '#7A4988');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('DARK VIOLET', '#710193');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('BOYSENBERRY', '#630436');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('ELECTRIC LAVENDER', '#E39FF6');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PLUM', '#601A35');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('STRONG MAGENTA', '#A1045A');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('DEEP LILAC', '#B65FCF');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('GRAPE', '#663046');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('ROYAL PERIWINKLE', '#BE93D4');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SANGRIA PURPLE', '#4D0F28');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('EGGPLANT', '#311432');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('JAZZBERRY JAM', '#67032F');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('IRIS', '#9867C5');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('HEATHER', '#9E7BB5');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('AMETHYST', '#A45EE5');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('RAISIN', '#290916');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('MEDIUM ORCHID', '#AF69EF');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('DARK MULBERRY', '#4C0121');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('DEEP WINE', '#2C041C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('THISTLE', '#D8BFD8');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('ORCHID', '#DA70D6');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('ELECTRIC VIOLET', '#8F00FF');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Medium Purple', '#9370DB');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Dark Orchid', '#9932CC');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Dark Magenta', '#8B008B');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Veronica', '#A020F0');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Heliotrope', '#DF73FF');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Purpureus', '#9A4EAE');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Northwestern Purple', '#4E2A84');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('KSU Purple', '#512888');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Pomp and Power', '#86608E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Mardi Gras', '#880085');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Eminence', '#6C3082');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Pansy Purple', '#78184A');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Palatinate', '#72246C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Dark Purple', '#301934');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Byzantium', '#702963');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('English Violet', '#563C5C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Affair', '#6F4685');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Long Distance', '#6F456E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Prince Charming', '#493F5E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Lipstick Stain', '#8E4785');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Pompadour', '#720058');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Grape Color', '#6F2DA8');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Pizza Edge', '#9A2CA0');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Tyrian Purple', '#66023C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Ultra Violet', '#645394');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Electric Purple', '#BF00FF');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Studio', '#7851A9');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PINK', '#F699CD');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('ROSE', '#FC94AF');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('FRENCH FUCHSIA', '#FC46AA');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PUNCH', '#F25278');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('BLUSH PINK', '#FEC5E5');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('WATERMELON', '#FE7F9C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('FLAMINGO', '#FDA4BA');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('ROUGE', '#F26B8A');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('LIGHT SALMON', '#FDAB9F');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CORAL PINK', '#FE7D6A');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PEACH', '#FC9483');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('STRAWBERRY', '#FC4C4E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('ROSEWOOD', '#9E4244');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('LEMONADE', '#FCBACB');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('TAFFY', '#FA86C4');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('BUBBLEGUM', '#FD5DA8');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('BALLET SLIPPER', '#F79AC0');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('LEMONADE CREPE', '#F2B8C6');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('MAGENTA PROCESS', '#E11584');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('HOT PINK', '#FF1694');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('AMARANTH PINK', '#E52B50');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('RAZZMATAZZ', '#E3256B');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CARNATION', '#FFA6C9');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Salmon', '#FF9999');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Light pink', '#FFB6C1');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Pastel pink', '#FFD1DC');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Cherry blossom', '#FFB7C5');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Baby pink', '#F4C2C2');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Dark pink', '#E75480');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Bright pink', '#FF007F');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Neon pink', '#FF6EC7');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Magenta', '#FF00FF');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Tulip pink', '#FF8E8E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Piggy Pink', '#FDDDE6');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Cotton Candy', '#FFBCD9');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Cameo pink', '#EFBBCC');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('French pink', '#F64A8A');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Persian pink', '#F77FBE');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Candy pink', '#E4717A');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Cherry pink', '#DE3163');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Dark Terra cotta', '#CC4E5C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Deep Pink', '#FF1493');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Dust Storm', '#E5CCC9');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Nadeshiko Pink', '#F6ADC6');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Wild Strawberry', '#FF43A4');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Rubine Red', '#D10056');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Hollywood Cerise', '#F400A1');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Mexican Pink', '#E4007C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Steel Pink', '#CC3366');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Rose Bonbon', '#F9429E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('BROWN OIL', '#231709');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('ROASTED COFFEE', '#4B371C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('MOCHA', '#3C280D');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PEANUT BROWN', '#795C34');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CAROB', '#362511');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('HICKORY', '#371D10');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('WOOD', '#3F301D');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PECAN', '#4A2511');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('WALNUT', '#432616');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CARAMEL', '#65350F');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('GINGERBREAD', '#5E2C04');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SYRUP', '#481F01');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('DARK CHOCOLATE', '#2E1503');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('TORTILLA', '#9A7B4F');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('UMBER', '#352315');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('TAWNY', '#80471C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('BRUNETTE', '#3B1E08');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CINNAMON BROWN', '#652A0E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PENNY', '#532915');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CEDAR BROWN', '#4A3728');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('BEAVER', '#9F8170');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('BISTRE', '#3D2B1F');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('BOLE', '#79443B');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Burnt umber', '#8A3324');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Cafe au lait', '#A67B5B');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Cafe noir', '#4B3621');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Coffee', '#6F4E37');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Deep coffee', '#704241');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Copper', '#B87333');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Dark brown', '#654321');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Taupe', '#483C32');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Ecru', '#C2B280');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Golden brown', '#996515');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Khaki', '#C3B091');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Ochre', '#CC7722');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Light brown', '#B5651D');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Saddle brown', '#8B4513');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Russet', '#80461B');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Sienna', '#A0522D');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Antique brass', '#CD9575');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Burlywood', '#DEB887');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Peru', '#CD853F');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Tumbleweed', '#DEAA88');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Dark vanilla', '#D1BEA8');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Wood brown', '#C19A6B');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Chamoisee', '#A0785A');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Deer', '#BA8759');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Dirt', '#9B7653');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Coconut', '#965A3E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Windsor tan', '#A75502');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('BLACK', '#000000');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('EBONY', '#080402');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CROW', '#0D0907');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CHARCOAL', '#28231D');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('MIDNIGHT', '#040406');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('INK', '#070504');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('RAVEN', '#050301');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('OIL', '#050100');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('GREASE', '#0A0806');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('ONYX', '#030104');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PITCH', '#030001');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SOOT', '#160D08');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SABLE', '#060606');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('JET BLACK', '#030303');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('COAL', '#0C0908');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('METAL', '#0E0C0A');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('OBSIDIAN', '#020403');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('JADE', '#000302');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SPIDER', '#040200');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('LEATHER', '#0B0705');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('ASPHALT', '#0C0404');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('LICORICE', '#1A1110');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('NIGHT', '#0C090A');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Charleston green', '#232B2B');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Dark jungle green', '#1A2421');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Eerie black', '#1B1B1B');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Raisin black', '#242124');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Smoky black', '#100C08');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Black Rock', '#010127');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Neutral Black', '#0B0B0B');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Black Denim', '#191C27');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Vampire Black', '#0F0404');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Cool Black', '#151922');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Frost Black', '#191C20');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Power Black', '#0E0C01');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Premium Black', '#100E09');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Black Magic', '#0B0510');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Alien Black', '#1A2228');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Black Chocolate', '#1B1811');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Gothic Grape', '#120321');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Metropolis', '#1A1A1A');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Night Shadow', '#1C1C1C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Dark Raisin', '#1A0F0F');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Tea Bag', '#161311');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Tech Black', '#0D0E0E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Dull Black', '#161616');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Dark Black', '#010203');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Natural Black', '#07000B');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Retro Black', '#1F201F');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Deep Black', '#050203');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('GRAY', '#808080');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SHADOW', '#373737');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('GRAPHITE', '#594D5B');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('IRON', '#322D31');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PEWTER', '#696880');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CLOUD', '#C5C6D0');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SILVER', '#ADADC9');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SMOKE', '#59515E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('DARK SLATE', '#3E3D53');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('ANCHOR', '#41424C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('ASH', '#564C4D');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PORPOISE', '#4D4C5C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('DOVE', '#7C6E7F');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('FOG', '#655967');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('FLINT', '#7F7D9C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CHARCOAL GRAY', '#232023');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PEBBLE', '#333333');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('LEAD', '#3F3F4E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('COIN', '#9897A9');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('FOSSIL', '#787276');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('ARSENIC', '#3B444B');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('NEVADA', '#666A6D');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SCORPION', '#5E5E5E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Battleship Gray', '#848482');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Carbon Gray', '#625D5D');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Davy’s Gray', '#555555');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Dim Gray', '#696969');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Gray Cloud', '#B6B6B4');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Gray Dolphin', '#5C5858');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Gray Wolf', '#504A4B');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Gunmetal', '#2A3439');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Marengo', '#4C5866');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Medium Gray', '#BEBEBE');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Nickel', '#727472');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Stone Gray', '#928E85');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Outer Space', '#414A4C');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Rocket Metallic', '#8A7F8D');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Silver Chalice', '#ACACAC');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Smokey Gray', '#726E6D');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Sonic Gray', '#757575');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Spanish Gray', '#989898');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Taupe Gray', '#8B8589');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Vampire Gray', '#565051');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('X11 Gray', '#BBBCB6');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Dark Silver', '#746D69');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Pastel Gray', '#CCCDC6');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Misty Gray', '#BCC2C2');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Vintage Gray', '#989692');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Zombie Gray', '#63645E');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Perfect Gray', '#A1A1A1');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('WHITE', '#FFFFFF');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PEARL', '#FBFCF8');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('ALABASTER', '#FEF9F3');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SNOW', '#F5FEFD');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PALE IVORY', '#FDF6E4');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CREAM', '#FFFADA');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('EGGSHELL', '#FFF9E3');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('COTTON', '#FBFBF9');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('CHIFFON', '#FBFAF2');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PINK SALT', '#F8EEEC');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('LACE', '#F8F2ED');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('COCONUT MILK', '#FFF1E6');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('LINEN', '#F3EAD3');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('BONE', '#E7DECC');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('DAISY', '#FAFAFA');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('POWDER', '#FBFCFA');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('FROST', '#ECFBFC');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PORCELAIN', '#FFFEFC');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PARCHMENT', '#FBF5DF');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('RICE', '#FAF5EF');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('SEASHELL', '#FFF5EE');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('PEPPERMINT', '#F1F9EC');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('MILK', '#FDFFF5');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Ghost white', '#F8F8FF');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('White smoke', '#F5F5F5');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Baby powder', '#FEFEFA');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Ivory', '#FFFFF0');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Floral white', '#FFFAF0');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Link White', '#ECF3F9');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Rose White', '#FFFAFA');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Vista White', '#FDFCFA');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Snow Drift', '#F8FBF8');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Island Spice', '#FFFCEC');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Soft Peach', '#F6F1F4');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Harp', '#EBF5F0');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Cough Mixture', '#F6F4F1');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Cup Cake', '#EBF6F7');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Magnolia', '#F8F4FF');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Anti-Flash White', '#F2F3F4');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Cascading White', '#F7F5F6');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Cotton Ball', '#F2F7FD');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Photon White', '#F8F8E8');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('White Heat', '#FDF9EF');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Whitewash', '#FEFFFC');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Shadow White', '#EEF1EA');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Acoustic White', '#EFECE1');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Aircraft White', '#EDF2F8');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Ceramic', '#FCFFF9');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Bright White', '#F4F5F0');
INSERT INTO dbo.[Colour] (Name, Value) VALUES ('Brilliant White', '#EDF1FE');

INSERT INTO dbo.[UserTYpe](Name,IconPictureId) VALUES ('Employee',8);
INSERT INTO dbo.[UserTYpe](Name,IconPictureId) VALUES ('Customer',9);

INSERT INTO dbo.[Status] (IconPictureId, DisplayName) VALUES (4, 'Received');
INSERT INTO dbo.[Status] (IconPictureId, DisplayName) VALUES (5, 'Payment Processed');
INSERT INTO dbo.[Status] (IconPictureId, DisplayName) VALUES (6, 'Payment Error');
INSERT INTO dbo.[Status] (IconPictureId, DisplayName) VALUES (7, 'Processed');
INSERT INTO dbo.[Status] (IconPictureId, DisplayName) VALUES (19, 'ReviewApprovalPending');
INSERT INTO dbo.[Status] (IconPictureId, DisplayName) VALUES (21, 'ReviewApproved');
INSERT INTO dbo.[Status] (IconPictureId, DisplayName) VALUES (22, 'ReviewRejected');

INSERT INTO dbo.[Platform] (Name) VALUES ('Macintosh');
INSERT INTO dbo.[Platform] (Name) VALUES ('Windows');
INSERT INTO dbo.[Platform] (Name) VALUES ('Nintendo');
INSERT INTO dbo.[Platform] (Name) VALUES ('Playstation');
INSERT INTO dbo.[Platform] (Name) VALUES ('XBox');

INSERT INTO dbo.[ApprovalStatus] (IconPictureId, Name) VALUES (14, 'Approved');
INSERT INTO dbo.[ApprovalStatus] (IconPictureId, Name) VALUES (15, 'Denied');
INSERT INTO dbo.[ApprovalStatus] (IconPictureId, Name) VALUES (16, 'Awaiting Approval');
INSERT INTO dbo.[ApprovalStatus] (IconPictureId, Name) VALUES (17, 'Blocked');
INSERT INTO dbo.[ApprovalStatus] (IconPictureId, Name) VALUES (19, 'AwaitingReview');
INSERT INTO dbo.[ApprovalStatus] (IconPictureId, Name) VALUES (21, 'ReviewApproved');
INSERT INTO dbo.[ApprovalStatus] (IconPictureId, Name) VALUES (22, 'ReviewRejected');

INSERT INTO dbo.[Gender] (DisplayName) VALUES ('Male');
INSERT INTO dbo.[Gender] (DisplayName) VALUES ('Female');
INSERT INTO dbo.[Gender] (DisplayName) VALUES ('Non-binary');
INSERT INTO dbo.[Gender] (DisplayName) VALUES ('Non-confirming');
INSERT INTO dbo.[Gender] (DisplayName) VALUES ('Genderqueer');
INSERT INTO dbo.[Gender] (DisplayName) VALUES ('Trans');
INSERT INTO dbo.[Gender] (DisplayName) VALUES ('Two-spirit');
INSERT INTO dbo.[Gender] (DisplayName) VALUES ('Not to answer');

INSERT INTO dbo.[Genre] (Name, Type) VALUES ('Action', 1);
INSERT INTO dbo.[Genre] (Name, Type) VALUES ('Action-adventure', 1);
INSERT INTO dbo.[Genre] (Name, Type) VALUES ('Adventure', 1);
INSERT INTO dbo.[Genre] (Name, Type) VALUES ('RPG', 1);
INSERT INTO dbo.[Genre] (Name, Type) VALUES ('Simulation', 1);
INSERT INTO dbo.[Genre] (Name, Type) VALUES ('Strategy', 1);
INSERT INTO dbo.[Genre] (Name, Type) VALUES ('Sports', 1);
INSERT INTO dbo.[Genre] (Name, Type) VALUES ('Puzzle', 1);
INSERT INTO dbo.[Genre] (Name, Type) VALUES ('Idle', 1);
INSERT INTO dbo.[Genre] (Name, Type) VALUES ('Hat', 2);
INSERT INTO dbo.[Genre] (Name, Type) VALUES ('Shirt', 2);
INSERT INTO dbo.[Genre] (Name, Type) VALUES ('Pants', 2);
INSERT INTO dbo.[Genre] (Name, Type) VALUES ('Bag', 2);

INSERT INTO dbo.[GenreType] (Name) VALUES ('Game');
INSERT INTO dbo.[GenreType] (Name) VALUES ('Merchandise');

INSERT INTO dbo.[User] (UserTypeId, EmailAddress, Password, EmailValidationToken, EmailValid, LoginAttempts, DisplayName, FirstName, LastName) VALUES (2, 'testemp@test.ca', 'ChocolistAdmin321!', '', 1, 0, 'Admin Employee', 'Admin', 'Employee');
